"""add relacionamento usuario/grupo

Revision ID: 4b2098cc1e05
Revises: d6fb4db40bd9
Create Date: 2026-01-03 08:46:42.809411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2098cc1e05'
down_revision: Union[str, Sequence[str], None] = 'd6fb4db40bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('grupo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'grupos_familiares', ['grupo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'grupo_id')
    # ### end Alembic commands ###
