"""add coluna modified_at

Revision ID: 5494af4cc9ed
Revises: d4bdf72b287d
Create Date: 2025-12-25 12:53:56.365401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5494af4cc9ed'
down_revision: Union[str, Sequence[str], None] = 'd4bdf72b287d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carteiras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carteiras', schema=None) as batch_op:
        batch_op.drop_column('modified_at')

    # ### end Alembic commands ###
