"""Criação inicial das tabelas

Revision ID: 8818a8f52d7c
Revises: 
Create Date: 2025-12-19 23:26:53.171323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8818a8f52d7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carteiras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Lancamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuarios')
    op.drop_table('Lancamentos')
    op.drop_table('Carteiras')
    # ### end Alembic commands ###
