"""added created, updated fields

Revision ID: b6fb9056d4ba
Revises: c180bd5e5167
Create Date: 2025-12-29 10:54:47.720676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6fb9056d4ba'
down_revision: Union[str, Sequence[str], None] = 'c180bd5e5167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_column('created_at_utc')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_column('created_at_utc')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
