"""add coluna lider_familiar

Revision ID: be2370634419
Revises: 4b2098cc1e05
Create Date: 2026-01-05 13:35:45.957672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2370634419'
down_revision: Union[str, Sequence[str], None] = '4b2098cc1e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('lider_familiar', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'lider_familiar')
    # ### end Alembic commands ###
