"""created grupo familiar table

Revision ID: c180bd5e5167
Revises: 332de8895479
Create Date: 2025-12-26 13:15:11.354261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c180bd5e5167'
down_revision: Union[str, Sequence[str], None] = '332de8895479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_familiares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_familiar_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'grupos_familiares', ['grupo_familiar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteiras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grupo_familiar_id')

    op.drop_table('grupos_familiares')
    # ### end Alembic commands ###
