"""add coluna teste data

Revision ID: eb6db9f8b01c
Revises: 312bc0c44997
Create Date: 2025-12-24 20:25:27.426548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6db9f8b01c'
down_revision: Union[str, Sequence[str], None] = '312bc0c44997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carteiras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teste_data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carteiras', schema=None) as batch_op:
        batch_op.drop_column('teste_data')

    # ### end Alembic commands ###
